# Generated by Django 3.2.11 on 2023-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('discription', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
